name: ci-fedora

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        builds:
        - "docker buildx build --platform linux/amd64,linux/arm64 --output \"type=image,push=true\" --file ./Dockerfile.fedora . --build-arg APISIX_VERSION=2.13.0 --tag dyrnq/apisix:2.13.0-fedora"
        - "docker buildx build --platform linux/amd64,linux/arm64 --output \"type=image,push=true\" --file ./Dockerfile.fedora . --build-arg APISIX_VERSION=2.13.1 --tag dyrnq/apisix:2.13.1-fedora"
        - "docker buildx build --platform linux/amd64,linux/arm64 --output \"type=image,push=true\" --file ./Dockerfile.fedora . --build-arg APISIX_VERSION=2.13.2 --tag dyrnq/apisix:2.13.2-fedora"
        - "docker buildx build --platform linux/amd64,linux/arm64 --output \"type=image,push=true\" --file ./Dockerfile.fedora . --build-arg APISIX_VERSION=2.12.0 --tag dyrnq/apisix:2.12.0-fedora"
        - "docker buildx build --platform linux/amd64,linux/arm64 --output \"type=image,push=true\" --file ./Dockerfile.fedora . --build-arg APISIX_VERSION=2.12.1 --tag dyrnq/apisix:2.12.1-fedora"
        - "docker buildx build --platform linux/amd64,linux/arm64 --output \"type=image,push=true\" --file ./Dockerfile.fedora . --build-arg APISIX_VERSION=2.11.0 --tag dyrnq/apisix:2.11.0-fedora"
        - "docker buildx build --platform linux/amd64,linux/arm64 --output \"type=image,push=true\" --file ./Dockerfile.fedora . --build-arg APISIX_VERSION=2.10.3 --tag dyrnq/apisix:2.10.3-fedora"
        - "docker buildx build --platform linux/amd64,linux/arm64 --output \"type=image,push=true\" --file ./Dockerfile.fedora . --build-arg APISIX_VERSION=2.10.4 --tag dyrnq/apisix:2.10.4-fedora"
        - "docker buildx build --platform linux/amd64,linux/arm64 --output \"type=image,push=true\" --file ./Dockerfile.fedora . --build-arg APISIX_VERSION=2.10.5 --tag dyrnq/apisix:2.10.5-fedora"
        - "docker buildx build --platform linux/amd64,linux/arm64 --output \"type=image,push=true\" --file ./Dockerfile.fedora . --build-arg APISIX_VERSION=2.14.1 --tag dyrnq/apisix:2.14.1-fedora"



    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build dockerfile (with push)
        run: |
          ${{ matrix.builds }}
