name: ci

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt-get install -y make ruby ruby-dev rubygems build-essential
          sudo gem install --no-document fpm
          sudo apt-get install -y rpm

      - name: packaging APISIX(-local) with local code
        run: |          
          git clone https://github.com/api7/apisix-build-tools.git
          git clone https://github.com/apache/apisix.git
          ls -l
          pushd apisix-build-tools || exit
          make package type=rpm app=apisix version=master checkout=master image_base=centos image_tag=7 local_code_path=../apisix artifact=apisix-local
          popd > /dev/null || exit

      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build dockerfile (with push)
        run: |
          docker buildx build --platform linux/amd64 --output "type=image,push=true" --file ./Dockerfile.master . --build-arg APISIX_VERSION=master --tag dyrnq/apisix:master